### ISSUE TITLE
Design .cells file in the yaml format and implement a parser and a converter from .env

### ISSUE THREAD

**Issue by tomooda** [cormas/cormas#311]

**Comment by SergeStinckwich** [comment]
Example: 
```yaml
dimensions:	[10, 10]
closure: "closed"
connectivity: "four" 
attributes_def:
  - seed: nil
  - tree: boolean
attributes_values:
[[nil,nil],
[nil,nil],
[nil,nil],
...
```
